name: BuildBattle-OG
main: plugily.projects.buildbattle.Main
authors: [ PlugilyProjects, Tigerpanzer_02, Tigerpanzer, Plajer, TomTheDeveloper ]
version: ${version}
softdepend: [ My_Worlds, MyWorlds, Citizens, PlaceholderAPI, Parties, Spigot-Party-API-PAF, PartyAndFriends, ViaVersion, ProtocolSupport ]
api-version: ${apiVersion}

commands:
  buildbattle:
    description: BuildBattle-OG Commands
    usage: "§6Correct usage: /bb [option]"
    aliases: [ bb, buildb ]
  buildbattleadmin:
    description: BuildBattle-OG Admin Commands
    usage: "§6Correct usage: /bba [option]"
    aliases: [ bba, buildbadmin ]
  hub:
    description: Leave the BuildBattle lobby or game and return to the main world.

permissions:
  buildbattle.admin.*:
    default: op
    children:
      buildbattle.particles: true
      buildbattle.heads: true
      buildbattle.updatenotify: true
      buildbattle.admin: true
      buildbattle.admin.sign.create: true
      buildbattle.admin.sign.break: true
      buildbattle.admin.stopgame: true
      buildbattle.admin.addnpc: true
      buildbattle.admin.addsign: true
      buildbattle.admin.reload: true
      buildbattle.admin.forcestart: true
      buildbattle.admin.forcestart.theme: true
      buildbattle.admin.addplot: true
      buildbattle.admin.removeplot: true
      buildbattle.admin.plotwand: true
      buildbattle.admin.list: true
      buildbattle.admin.delete: true
      buildbattle.admin.create: true
      buildbattle.admin.settheme: true
      buildbattle.admin.supervotes.manage: true
      buildbattle.command.bypass: true
